# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-13 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(default='No proporcionada', max_length=250)),
                ('categoria', models.CharField(choices=[('1', 'Economico'), ('2', 'Valor'), ('3', 'Calidad'), ('4', 'Superior'), ('5', 'Excepcional')], default='1', max_length=1)),
            ],
        ),
    ]
