# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-16 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitacion', '0002_habitacion_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField()),
                ('valor_reserva', models.IntegerField()),
                ('estado_reserva', models.CharField(choices=[('1', 'Disponible'), ('2', 'Reservada')], default='1', max_length=1)),
                ('habitacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='habitacion.Habitacion')),
            ],
        ),
    ]
