# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-13 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('capacidad', models.IntegerField()),
                ('tipo', models.CharField(choices=[('1', 'Sola'), ('2', 'Doble')], default='1', max_length=1)),
            ],
        ),
    ]
