# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-13 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
        ('habitacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotel'),
        ),
    ]
