# Generated by Django 2.0.6 on 2018-06-23 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('capacidad', models.IntegerField()),
                ('tipo', models.CharField(choices=[('1', 'Sola'), ('2', 'Doble')], default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(default='No proporcionada', max_length=250)),
                ('categoria', models.CharField(choices=[('1', 'Economico'), ('2', 'Valor'), ('3', 'Calidad'), ('4', 'Superior'), ('5', 'Excepcional')], default='1', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='habitacion',
            name='hotel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotel'),
        ),
    ]
