# Generated by Django 2.0.6 on 2018-06-23 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20180623_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acompanante',
            name='huesped',
        ),
        migrations.AddField(
            model_name='huesped',
            name='acompanante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Acompanante'),
        ),
    ]
