# Generated by Django 2.0.6 on 2018-06-23 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_auto_20180623_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotel'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='tipo_habitacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.TipoHabitacion'),
        ),
    ]
