# Generated by Django 2.0.6 on 2018-06-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_auto_20180623_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanante',
            name='ci',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='acompanante',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='ci',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_ingreso',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_salida',
            field=models.DateField(),
        ),
    ]
